# Generated by Django 4.1.5 on 2023-07-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('password', models.BinaryField(max_length=255)),
                ('role_id', models.IntegerField()),
                ('zip_code', models.IntegerField()),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LandOwner',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('carbon_project_id', models.IntegerField()),
                ('wood_quality', models.CharField(max_length=510)),
                ('species', models.CharField(max_length=510)),
                ('year_of_harvest', models.DateField()),
                ('harvest_location', models.CharField(max_length=510)),
            ],
        ),
        migrations.CreateModel(
            name='Mill',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
