# Generated by Django 4.1.5 on 2023-07-21 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_landowner_options_alter_mill_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='landowner',
            table='landowner',
        ),
        migrations.AlterModelTable(
            name='mill',
            table='mill',
        ),
    ]
